### ISSUE TITLE
Use Merkle Trees for each backup digest

### ISSUE THREAD

**Issue by mster** [nick-nuti/Backup-Program#19]
Requires #21 

Represent the backup digest as a Merkle Tree.
https://en.wikipedia.org/wiki/Merkle_tree

Merkle trees will allow us to effectively determine differences between digests. From this, we may easily determine if any files have been modified, which would require modified files to be synced to the backend storage. 

Considerations:
1) Is it important to retain the original state of a file even after it has be modified? 
    * e.g.: Backup1.json from Downloads. User modifies a text file inside Downloads. Backup2.json includes the updated text file with modified contents. **Should we keep the original text file as a means of allowing the user to "step backwards in time"?** This would mean holding on to multiple copies of the same source content. 
2) Does each successive backup digest include a full Merkle Tree OR just the diff of the previous backup and the current state?
    * Full Merkle tree would be memory heavy on the digest side of things. 
    * Partial Merkle tree would require some additional work to reconstruct the full tree when a user asks for a specific backup. 
    * Memory vs Time?
3) What hashing algorithm are we using for nodes? SHA256? Consider portability. 

~REF #13~

**Comment by mster** [comment]
Can we create a new digest that references an old one? This way we could chain together digests that contain no-modifications.

**Comment by nick-nuti** [comment]
Wanted to note the following:
- The digest should probably be the same. Maybe get rid of the "writable" attribute and add a "sum" attribute.
- The hash should be made up of SHA256 data.
- Windows implementation can be found here: https://docs.microsoft.com/en-us/windows/win32/seccng/creating-a-hash-with-cng
- Linux should use OPENSSL
- I haven't looked into MAC yet.

**Comment by nick-nuti** [comment]
With respect to your considerations:
1. I think that we need to set clear guidelines as to what file changes are major enough to keep (like if there are spaces or returns at the end of a file that don't modify the contents), but in general I think we should be keeping files that have differences. 
2. That is a good question. I think we should discuss this; I was going to write out a response but I realized that as we accumulate more backups, this subject becomes complicated.
3.  I talked to Joe about this, and we should be using SHA256 because it's essentially on every major platform at this point.
